### ISSUE TITLE
两个小建议

### ISSUE THREAD

**Issue by InTka** [VirtualHotBar/HotPE-#55]
![屏幕截图 2024-06-27 071115](https://github.com/VirtualHotBar/HotPEToolBox/assets/167493374/e58cd5cb-6f88-4847-9e6d-f544fe26ade6)
安全软件这栏可以放360杀毒7.0（注意不是5.0，因为5.0有广告），7.0我用着一星期了完全没广告，从功能上来说就是阉割掉了臃肿组件的360安全卫士，除了界面有点丑其他其实都挺好（因为360安全卫士极速版似乎也有点小广告了，转用360杀毒才发现忒好用了）

还有就是那啥HotPE卸载的话直接整个HotPE_Client文件夹删掉就好了对吧（不知道你们会不会往其他地方塞文件，你们官网似乎也没写怎么删除，建议在下载界面就加上怎么卸载（某大厂Tencent的应用宝就挺喜欢乱放小文件，虽然文件不大但是挺恶心人））

**Comment by VirtualHotBar** [comment]
1.你自己需要相关模块的话，可以自己打包并投稿（详细看文档）。
2.HotPE_Client对系统是无入侵的（也就是可以直接删除软件目录以卸载软件）。

还有就是，你这个issue的内容和标题不符，内容不应该出现在这里。你可以加群问这些问题
