### ISSUE TITLE
下载错误

### ISSUE THREAD

**Issue by CrazyDoge666** [VirtualHotBar/HotPE-#58]
一直模块下载出错。更换网络环境挂梯子也无效

下载出错: 07/28 10:09:52 [[1;31mERROR[0m] CUID#7 - Download aborted. URI=https://p0.hotpe.top/HotPE%E6%A8%A1%E5%9D%97/%E5%A4%87%E4%BB%BD%E8%BF%98%E5%8E%9F/EasyRC_%E4%BC%98%E6%8D%B7%E6%98%93_3.5.1.0_EasyRC%E6%98%AF%E5%B9%B4%E8%BD%BB%E4%BA%BA%E7%9A%84%E7%AC%AC%E4%B8%80%E6%AC%BE%E7%B3%BB%E7%BB%9F%E9%87%8D%E8%A3%85%E8%BD%AF%E4%BB%B6.HPM Exception: [HttpSkipResponseCommand.cc:254] errorCode=29 The response status is not successful. status=502 07/28 10:09:52 [[1;32mNOTICE[0m] Download GID#2b351d115b55857a not complete: F:/HotPEModule//EasyRC_浼樻嵎鏄揰3.5.1.0_EasyRC鏄勾杞讳汉鐨勭涓€娆剧郴缁熼噸瑁呰蒋浠�.HPM Download Results: gid |stat|avg speed |path/URI ======+====+===========+======================================================= 2b351d|ERR | 0B/s|F:/HotPEModule//EasyRC_浼樻嵎鏄揰3.5.1.0_EasyRC鏄勾杞讳汉鐨勭涓€娆剧郴缁熼噸瑁呰蒋浠�.HPM Status Legend: (ERR):error occurred. aria2 will resume download if the transfer is restarted. If there are any errors, then see the log file. See '-l' option in help/man page for details.

**Comment by VirtualHotBar** [comment]
因为备份文件被误报(onedrive)，可寻找替代模块或自己打包。

**Comment by VirtualHotBar** [comment]
9月将不再使用onedrive文件存储，解决此问题
