### ISSUE TITLE
EasyImageX下载失败

### ISSUE THREAD

**Issue by wzsthehill** [VirtualHotBar/HotPE-#59]
EasyImageX下载失败

`下载出错: 08/01 21:08:39 [[1;31mERROR[0m] CUID#7 - Download aborted. URI=https://p0.hotpe.top/HotPE%E6%A8%A1%E5%9D%97/%E5%A4%87%E4%BB%BD%E8%BF%98%E5%8E%9F/EasyImageX_VirtualHotBar_2.19.827.1718_IT%E5%A4%A9%E7%A9%BA%E5%87%BA%E5%93%81%E7%9A%84%E7%B3%BB%E7%BB%9F%E5%A4%87%E4%BB%BD%E8%BF%98%E5%8E%9F%E5%B7%A5%E5%85%B7.HPM Exception: [AbstractCommand.cc:351] errorCode=22 URI=https://hotes.sharepoint.cn/sites/yushu/_layouts/15/download.aspx?UniqueId=3b2dcf4c-7c09-42d6-98cd-8fbde08e8089&Translate=false&tempauth=v1.eyJzaXRlaWQiOiIxOGQ5MTU3Ny1lODUyLTRlNjgtYjQ0Yi04OTNjYTY1YmU3YWMiLCJhcHBfZGlzcGxheW5hbWUiOiJ5dXNodSIsImFwcGlkIjoiZmJmMDdmMjYtY2Y3Zi00M2Y1LWE2YzUtMjg5Zjg3OTJhYzAyIiwiYXVkIjoiMDAwMDAwMDMtMDAwMC0wZmYxLWNlMDAtMDAwMDAwMDAwMDAwL2hvdGVzLnNoYXJlcG9pbnQuY25AYWFhYjI2ZWQtYmI0YS00ZTUxLWE0ZTMtY2QwNzMzMTEwZTMyIiwiZXhwIjoiMTcyMjUyMTEwOSJ9.CgoKBHNuaWQSAjY0EgsIiK6srpONmT0QBRoMNDAuNzIuNzQuMTk3KixodnJRTTFJR2NveHRyNzdsc0czT2k4R2gyS25Mb3ZJVWthV0F6djBZUGkwPTB_OAFCEKFCA4LlIAAAHt2MAjDQzbFKEGhhc2hlZHByb29mdG9rZW5yKTBoLmZ8bWVtYmVyc2hpcHwxMDAzMzIzMGVjMzZhMjIyQGxpdmUuY29tegEyggESCe0mq6pKu1FOEaTjzQczEQ4ykgEDQmFymgEDSG90ogEhaG90YmFyQGhvdGVzLnBhcnRuZXIub25tc2NoaW5hLmNuqgEQMTAwMzMyMzBFQzM2QTIyMrIBDmFsbGZpbGVzLndyaXRlyAEB.xKjC63LCeqp33gGLTNw8I5ibo_gaH6Dmg5mCThLhkEQ&ApiVersion=2.0 -> [HttpSkipResponseCommand.cc:269] errorCode=22 The response status is not successful. status=403 08/01 21:08:39 [[1;32mNOTICE[0m] Download GID#fd42ed3aacdc96b8 not complete: F:/HotPEModule//EasyImageX_VirtualHotBar_2.19.827.1718_IT澶╃┖鍑哄搧鐨勭郴缁熷浠借繕鍘熷伐鍏�.HPM Download Results: gid |stat|avg speed |path/URI ======+====+===========+======================================================= fd42ed|ERR | 0B/s|F:/HotPEModule//EasyImageX_VirtualHotBar_2.19.827.1718_IT澶╃┖鍑哄搧鐨勭郴缁熷浠借繕鍘熷伐鍏�.HPM Status Legend: (ERR):error occurred. aria2 will resume download if the transfer is restarted. If there are any errors, then see the log file. See '-l' option in help/man page for details.`

**Comment by VirtualHotBar** [comment]
https://github.com/VirtualHotBar/HotPEToolBox/issues/58
