### ISSUE TITLE
希望能支持SMB1.0-3.0，进一步把能区动网卡的功能扩大

### ISSUE THREAD

**Issue by bingodd2** [VirtualHotBar/HotPE-#60]
作为一个几十年的装机老手，真的很佩服作者一个高中生就能制作出能直接驱动网卡的PE，这是我之前见所未见的，
    但是我装好(V2.7.240201版本)之后却很遗憾地发现：居然不支持SMB/CIFS/Samba协议，具体问题是在资源管理器中输入：\\192.168.X.X后提示错误，这协议应该是历代微软件操作系统都原生支持的了，在我或者现在许多公司的使用环境下，都会在内网有NAS文件服务器的，这样重做系统时的镜像，就可以在PE环境下从内网中获取了，
    又由于许多电脑到了要重装系统时就无法获取镜像文件了，而用U盘又太慢了(千兆内网能至少50MB/S速度)，如果这个能驱动网卡PE能支持SMB的话，就可以在PE环境下通过资源管理器，快速地从内网的NAS中，复制通常几个GB大小的镜像文件了。

**Comment by VirtualHotBar** [comment]
可自行用模块实现
